name: Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        id: setupJava
        uses: actions/setup-java@v1
        with:
          java-version: 9
      - name: Print Environment
        run: env
      - name: Print Output
        run: echo "steps.setupJava:\ ${{ toJson(steps.setupJava) }}"
